apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: backup-autoquiz-mysql-pvc-workflow-template 
spec:
  entrypoint: backup-resource
  templates:
    - name: backup-resource
      inputs:
        parameters:
          - name: backup-id
      script:
        image: midknight24/restic
        command: ["bash"]
        volumeMounts:
          - name: backup-repo
            mountPath: /autoquiz-mysql-pvc/backup
            subPath: autoquiz-mysql-pvc
          - name: autoquiz-mysql-pvc-source
            mountPath: /source/autoquiz-mysql-pvc
        source: |
          #!/bin/sh
          set -e
          export RESTIC_REPOSITORY=/autoquiz-mysql-pvc/backup
          export RESTIC_PASSWORD=abcd1234
          restic init || true
          restic backup --host autoquiz-mysql-pvc --tag {{inputs.parameters.backup-id}} /source/autoquiz-mysql-pvc
          restic snapshots
          restic forget --keep-last 3 --prune

---

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: backup-autoquiz-test-pvc-workflow-template 
spec:
  entrypoint: backup-resource
  templates:
    - name: backup-resource
      inputs:
        parameters:
          - name: backup-id
      script:
        image: midknight24/restic
        command: ["bash"]
        volumeMounts:
          - name: backup-repo
            mountPath: /autoquiz-test-pvc/backup
            subPath: autoquiz-test-pvc
          - name: autoquiz-test-pvc-source
            mountPath: /source/autoquiz-test-pvc
        source: |
          #!/bin/sh
          set -e
          export RESTIC_REPOSITORY=/autoquiz-test-pvc/backup
          export RESTIC_PASSWORD=abcd1234
          restic init || true
          restic backup --host autoquiz-test-pvc --tag {{inputs.parameters.backup-id}} /source/autoquiz-test-pvc
          restic snapshots
          restic forget --keep-last 3 --prune
          
