apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: autoquiz-manager-backup-workflow-
spec:
  serviceAccountName: backup-sa
  entrypoint: backup
  volumes:
    - name: backup-repo
      persistentVolumeClaim:
        claimName: autoquiz-backup-pvc
    - name: autoquiz-mysql-pvc-source
      persistentVolumeClaim:
        claimName: autoquiz-mysql-pvc
    - name: autoquiz-test-pvc-source
      persistentVolumeClaim:
        claimName: autoquiz-test-pvc
  templates:
  - name: backup
    steps:                              
      - - name: pause-resources
          templateRef:                  
            name: pause-workflow-template 
            template: pause-resources
          arguments:
            parameters:
              - name: resources
                value: |
                  [
                    {"name": "deployment/autoquiz-pub"},
                    {"name": "deployment/autoquiz-quiz"},
                    {"name": "statefulset/autoquiz-mysql"}
                  ]
      - - name: backup-autoquiz-mysql-pvc
          templateRef:                  
            name: backup-autoquiz-mysql-pvc-workflow-template
            template: backup-resource
          arguments:
            parameters:
              - name: backup-id
                value: "{{workflow.creationTimestamp}}"
        - name: backup-autoquiz-test-pvc
          templateRef:                  
            name: backup-autoquiz-test-pvc-workflow-template
            template: backup-resource
          arguments:
            parameters:
              - name: backup-id
                value: "{{workflow.creationTimestamp}}"
      - - name: resume-resources
          templateRef:                  
            name: resume-workflow-template
            template: resume-resources
          arguments:
            parameters:
              - name: resources
                value: |
                  [
                    {"name": "deployment/autoquiz-pub", "replica": 3},
                    {"name": "deployment/autoquiz-quiz", "replica": 3},
                    {"name": "statefulset/autoquiz-mysql", "replica": 1}
                  ]