apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: autoquiz-manager-restore-workflow-
spec:
  serviceAccountName: backup-sa
  entrypoint: restore
  volumes:
    - name: backup-repo
      persistentVolumeClaim:
        claimName: autoquiz-backup-pvc
    - name: restore-location
      persistentVolumeClaim:
        claimName: autoquiz-mysql-pvc
  templates:
  - name: restore
    steps:                              
      - - name: pause-resources
          templateRef:                  
            name: pause-workflow-template 
            template: pause-resources
          arguments:
            parameters:
              - name: resources
                value: |
                  [
                    {"name": "deployment/autoquiz-pub"},
                    {"name": "deployment/autoquiz-quiz"},
                    {"name": "deployment/autoquiz-user"},
                    {"name": "statefulset/autoquiz-mysql"}
                  ]
      - - name: restore-autoquiz-mysql-pvc
          templateRef:                  
            name: restore-autoquiz-mysql-pvc-workflow-template
            template: restore-resource
          arguments:
            parameters:
              - name: backup-id
                value: 2025-09-29T14:13:25Z
        - name: restore-autoquiz-test-pvc
          templateRef:
            name: restore-autoquiz-test-pvc-workflow-template
            template: restore-resource
          arguments:
            parameters:
              - name: backup-id
                value: 2025-09-29T14:07:06Z 
      - - name: resume-resources
          templateRef:                  
            name: resume-workflow-template
            template: resume-resources
          arguments:
            parameters:
              - name: resources
                value: |
                  [
                    {"name": "deployment/autoquiz-pub", "replica": 3},
                    {"name": "deployment/autoquiz-quiz", "replica": 3},
                    {"name": "deployment/autoquiz-user", "replica": 1},
                    {"name": "statefulset/autoquiz-mysql", "replica": 1}
                  ]