apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pause-workflow-
spec:
  entrypoint: pause-resources
  serviceAccountName: backup-sa
  arguments:
    parameters:
      - name: resources
        value: |
          [
            {"name": "deployment/autoquiz-pub"},
            {"name": "deployment/autoquiz-quiz"},
            {"name": "statefulset/autoquiz-mysql"}
          ]
  workflowTemplateRef:
    name: pause-workflow-template
