#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@yaml/text-templated-strings

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: (@= data.values.appName @)-manage-restore-workflow-
  namespace: (@= data.values.namespace @)
spec:
  serviceAccountName: backup-sa
  entrypoint: restore
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 3600s
  volumes:
    - name: backup-repo
      persistentVolumeClaim:
        claimName: (@= data.values.repoPvc.name @)
    #@ for pvc in data.values.backupPvcs:
    - name: (@= pvc.name @)-source
      persistentVolumeClaim:
        claimName: (@= pvc.name @)
    #@ end
  arguments:
    parameters:
      - name: backup-id
        value: xxx #!这里填写需要恢复的备份ID，可以通过 showsnapshots 工作流查看 
  templates:
  - name: restore
    steps:                              
      - - name: pause-resources
          templateRef:                  
            name: pause-workflow-template 
            template: pause-resources
          arguments:
            parameters:
              - name: resources
                value: #@ json.encode([{"name": r.name, "timeout": getattr(r, 'timeout', '60s')} for r in data.values.workloads])
      - - name: restore-(@= data.values.backupPvcs[0].name @)
          templateRef:                  
            name: restore-(@= data.values.backupPvcs[0].name @)-workflow-template
            template: restore-resource
          arguments:
            parameters:
              - name: backup-id
                value: '{{workflow.parameters.backup-id}}'
        #@ for pvc in data.values.backupPvcs[1:]:
        - name: restore-(@= pvc.name @)
          templateRef:
            name: restore-(@= pvc.name @)-workflow-template
            template: restore-resource
          arguments:
            parameters:
              - name: backup-id
                value: '{{workflow.parameters.backup-id}}'
        #@ end
      - - name: resume-resources
          templateRef:                  
            name: resume-workflow-template
            template: resume-resources
          arguments:
            parameters:
              - name: resources
                value: #@ json.encode([{"name": r.name, "replica": r.replica} for r in data.values.workloads])