#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@yaml/text-templated-strings

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: (@= data.values.appName @)-manage-backup-workflow-
  namespace: (@= data.values.namespace @)
spec:
  serviceAccountName: backup-sa
  entrypoint: backup
  podGC:
    strategy: OnWorkflowSuccess
    deleteDelayDuration: 3600s
  volumes:
    - name: backup-repo
      persistentVolumeClaim:
        claimName: (@= data.values.repoPvc.name @)
    #@ for pvc in data.values.backupPvcs:
    - name: (@= pvc.name @)-source
      persistentVolumeClaim:
        claimName: (@= pvc.name @)
    #@ end
  templates:
  - name: backup
    steps:
      #@ for i, workload in enumerate(data.values.workloads):                              
      - - name: pause-resources-(@= str(i) @)
          templateRef:                  
            name: pause-workflow-template 
            template: pause-resources
          arguments:
            parameters:
              - name: resources
                value: #@ json.encode([{"name": r.name, "timeout": getattr(r, 'timeout', '60s') } for r in workload])
      #@ end
      - - name: backup-(@= data.values.backupPvcs[0].name @)
          templateRef:                  
            name: backup-(@= data.values.backupPvcs[0].name @)-workflow-template
            template: backup-resource
          arguments:
            parameters:
              - name: backup-id
                value: "{{workflow.creationTimestamp}}"
        #@ for pvc in data.values.backupPvcs[1:]:
        - name: backup-(@= pvc.name @)
          templateRef:                  
            name: backup-(@= pvc.name @)-workflow-template
            template: backup-resource
          arguments:
            parameters:
              - name: backup-id
                value: "{{workflow.creationTimestamp}}"
        #@ end
      #@ for i, workload in enumerate(data.values.workloads):
      - - name: resume-resources-(@= str(i) @)
          templateRef:                  
            name: resume-workflow-template
            template: resume-resources
          arguments:
            parameters:
              - name: resources
                value: #@ json.encode([{"name": r.name, "replica": r.replica} for r in workload])
      #@ end
