#@ load("@ytt:data", "data")
#@yaml/text-templated-strings

#@ for pvc in data.values.backupPvcs:
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: backup-(@= pvc.name @)-workflow-template 
  namespace: (@= data.values.namespace @)
spec:
  entrypoint: backup-resource
  templates:
    - name: backup-resource
      inputs:
        parameters:
          - name: backup-id
      script:
        image: midknight24/restic
        command: ["bash"]
        volumeMounts:
          - name: backup-repo
            mountPath: /(@= pvc.name @)/backup
            subPath: (@= pvc.name @)
          - name: (@= pvc.name @)-source
            mountPath: /source/(@= pvc.name @)
        source: |
          #!/bin/sh
          set -e
          export RESTIC_REPOSITORY=/(@= pvc.name @)/backup
          export RESTIC_PASSWORD=abcd1234
          restic unlock || true
          restic init || true
          restic backup --host (@= pvc.name @) --tag {{inputs.parameters.backup-id}} /source/(@= pvc.name @)
          restic snapshots
          restic forget --keep-last 3 --prune
#@ end
---
          
