apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: showsnapshots-workflow- 
spec:
  serviceAccountName: backup-sa
  entrypoint: showsnapshots
  volumes:
    - name: backup-dest
      persistentVolumeClaim:
        claimName: autoquiz-backup-pvc
    - name: backup-source
      persistentVolumeClaim:
        claimName: autoquiz-mysql-pvc
  templates:
    - name: showsnapshots
      script:
        image: midknight24/restic
        command: ["bash"]
        volumeMounts:
          - name: backup-dest
            mountPath: /autoquiz-mysql-pvc/backup
            subPath: autoquiz-mysql-pvc
          - name: backup-source
            mountPath: /source/autoquiz-mysql-pvc
        source: |
          #!/bin/sh
          set -e
          export RESTIC_REPOSITORY=/autoquiz-mysql-pvc/backup
          export RESTIC_PASSWORD=abcd1234
          restic snapshots
          
